### ISSUE TITLE
Some inference metrics will be helpful!

### ISSUE THREAD

**Issue by getabhishekified** [anuragranj/humanflow2#2]
Kindly provide some inference metrics for this algorithm.

**Comment by DavHoffmann** [comment]
Dear Abhishek, 

thanks for your question. The code to evaluate our models can be found in the script [test_humanflow.py](https://github.com/anuragranj/humanflow2/blob/master/test_humanflow.py). As is common practice for optical flow evaluation, we compute the end point error (epe). Additionally, we compute the Motion Compensated Intensity (MCI), referred to as "motion warping error" in the script.

In case you are interested in a comparison of different methods instead, please have a look at our [paper](https://arxiv.org/abs/1910.11667).
